# Generated by Django 6.1.1 on 2026-09-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('atendimento', 'Atendimento'), ('limpeza', 'Limpeza'), ('equipamentos', 'Equipamentos'), ('professores', 'Professores'), ('estrutura', 'Estrutura'), ('geral', 'Geral')], max_length=30)),
                ('nota', models.PositiveSmallIntegerField()),
                ('tipo_feedback', models.CharField(choices=[('elogio', 'Elogio'), ('sugestao', 'Sugestão'), ('reclamacao', 'Reclamação')], max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
