# Generated by Django 6.1.1 on 2026-09-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_avaliacao_localizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em análise'), ('resolvida', 'Resolvida')], default='pendente', max_length=20),
        ),
    ]
