# Generated by Django 6.1.1 on 2026-09-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_avaliacao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='categorias',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
