# Generated by Django 6.1.1 on 2026-09-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_avaliacao_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='tipos_feedback',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
