# Generated by Django 6.1.1 on 2026-09-17 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_avaliacao_tipos_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='funcionarios/')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='data_resolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='origem',
            field=models.CharField(choices=[('aluno', 'Aluno (QR)'), ('gerente', 'Gerente/Admin')], default='aluno', max_length=10),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='resolvido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_resolvidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='categoria',
            field=models.CharField(choices=[('atendimento', 'Atendimento'), ('limpeza', 'Limpeza'), ('equipamentos', 'Equipamentos'), ('professores', 'Professores'), ('estrutura', 'Estrutura'), ('geral', 'Geral')], default='geral', max_length=20),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='categorias',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('resolvida', 'Resolvida')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='tipo_feedback',
            field=models.CharField(choices=[('elogio', 'Elogio'), ('reclamacao', 'Reclamação'), ('sugestao', 'Sugestão')], default='elogio', max_length=20),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='tipos_feedback',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes', to='feedback.funcionario', verbose_name='Funcionário avaliado'),
        ),
    ]
