# Generated by Django 6.1.1 on 2026-09-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_funcionario_avaliacao_criado_por_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
    ]
