# Generated by Django 6.1.1 on 2026-10-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_alter_avaliacao_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaEnquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participa_aulas', models.CharField(blank=True, max_length=60, verbose_name='Participa das aulas coletivas')),
                ('aulas_favoritas', models.JSONField(blank=True, default=list, verbose_name='Aulas favoritas')),
                ('aulas_favoritas_outra', models.CharField(blank=True, max_length=150, verbose_name='Outra aula favorita')),
                ('aula_melhoria', models.CharField(blank=True, max_length=100, verbose_name='Aula que precisa de melhorias')),
                ('aula_falta', models.CharField(blank=True, max_length=255, verbose_name='Aula que sente falta')),
                ('novo_espaco', models.CharField(blank=True, max_length=100, verbose_name='Novo espaço mais desejado')),
                ('novo_espaco_outro', models.CharField(blank=True, max_length=150, verbose_name='Outro novo espaço')),
                ('sugestao_valor', models.TextField(blank=True, verbose_name='O que agregaria mais valor')),
                ('elogio_colaborador', models.TextField(blank=True, verbose_name='Elogio para colaboradores')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resposta da Enquete',
                'verbose_name_plural': 'Respostas da Enquete',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
