# Generated by Django 6.1.1 on 2026-10-07 19:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_respostaenquete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Equipamento')),
                ('identificador_qr', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador do QR Code')),
                ('localizacao', models.CharField(blank=True, max_length=120, verbose_name='Localização')),
                ('instrucoes', models.TextField(blank=True, verbose_name='Instruções gerais')),
                ('observacoes_seguranca', models.TextField(blank=True, verbose_name='Orientações de segurança')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipamento de treino',
                'verbose_name_plural': 'Equipamentos de treino',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Exercício')),
                ('instrucoes', models.TextField(verbose_name='Como executar')),
                ('video_url', models.URLField(blank=True, verbose_name='Link do vídeo autorizado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercicios', to='feedback.equipamento', verbose_name='Equipamento')),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Exercícios',
                'ordering': ['equipamento__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PlanoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Meu treino', max_length=120, verbose_name='Nome do plano')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Plano ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_treino', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Professor responsável')),
            ],
            options={
                'verbose_name': 'Plano de treino',
                'verbose_name_plural': 'Planos de treino',
                'ordering': ['aluno__username', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemPlanoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=1, verbose_name='Ordem')),
                ('series', models.PositiveSmallIntegerField(default=3, verbose_name='Séries')),
                ('repeticoes', models.CharField(default='10', max_length=40, verbose_name='Repetições')),
                ('descanso_segundos', models.PositiveSmallIntegerField(default=60, verbose_name='Descanso (segundos)')),
                ('carga', models.CharField(blank=True, help_text='Ex.: 15 kg. O sistema não calcula nem recomenda carga.', max_length=40, verbose_name='Carga orientada pelo professor')),
                ('observacoes', models.CharField(blank=True, max_length=255, verbose_name='Observações')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_plano', to='feedback.exercicio', verbose_name='Exercício')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='feedback.planotreino', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Exercício do plano',
                'verbose_name_plural': 'Exercícios do plano',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='exercicio',
            constraint=models.UniqueConstraint(fields=('equipamento', 'nome'), name='feedback_unique_exercise_per_equipment'),
        ),
    ]
