# Generated by Django 6.1.1 on 2026-10-08 10:57

from django.db import migrations, models


def migrar_funcoes_e_avaliacoes_existentes(apps, schema_editor):
    Funcao = apps.get_model("feedback", "Funcao")
    Funcionario = apps.get_model("feedback", "Funcionario")
    Avaliacao = apps.get_model("feedback", "Avaliacao")
    banco = schema_editor.connection.alias

    for funcionario in Funcionario.objects.using(banco).exclude(cargo="").iterator():
        for nome_funcao in funcionario.cargo.split(","):
            nome_funcao = nome_funcao.strip()
            if nome_funcao:
                funcao, _ = Funcao.objects.using(banco).get_or_create(
                    nome=nome_funcao
                )
                funcionario.funcoes.add(funcao)

    for avaliacao in Avaliacao.objects.using(banco).exclude(
        funcionario_id__isnull=True
    ).iterator():
        avaliacao.funcionarios.add(avaliacao.funcionario_id)


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_cadastrar_equipe_polo_fit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Função')),
            ],
            options={
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='funcionarios',
            field=models.ManyToManyField(blank=True, related_name='avaliacoes_multiplas', to='feedback.funcionario', verbose_name='Funcionários avaliados'),
        ),
        migrations.AddField(
            model_name='respostaenquete',
            name='funcionarios_elogiados',
            field=models.ManyToManyField(blank=True, related_name='elogios_enquetes', to='feedback.funcionario', verbose_name='Funcionários elogiados'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='funcoes',
            field=models.ManyToManyField(blank=True, related_name='funcionarios', to='feedback.funcao', verbose_name='Funções'),
        ),
        migrations.RunPython(
            migrar_funcoes_e_avaliacoes_existentes,
            migrations.RunPython.noop,
        ),
    ]
